application: igualitos
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin/?.*
  script: appadmin.py
      
- url: /appengine_admin_media
  static_dir: appengine_admin/media
  
- url: /.*
  script: application.py
  
